### ISSUE TITLE
Design solutions with eventual connectivity strategies and justify choices.

### ISSUE THREAD

**Issue by gnassar99** [Group22-MobileApp/Grupo22-Flutter#41]

**Comment by 4ndresp26** [comment]
Eventual connectivity strategies are implemented to:
login and be able to recognize failures in obtaining the authentication key in case of network problems.
User registration to be able to save user data in cache so that in case of not having internet the request is saved and the process is resumed when the internet returns
It is implemented in product search to limit queries to non-cached elements and the display of errors or empty containers.
